name: Test-Examples   # BSP Examples
on:
  workflow_dispatch:
  pull_request:
    branches: [main]
  push:
    branches: [main]
  schedule:
    - cron: '00 20 * * 6'

jobs:
  Test-Examples:                     # Install tools, build
    strategy:
      matrix:
        test: [
          { tool: GCC,   dir: ./DevKit-e7/Examples/Blinky_HE,            proj: Blinky_HE,           artifact: E7_Blinky_HE },
          { tool: AC6,   dir: ./DevKit-e7/Examples/Blinky_HE,            proj: Blinky_HE,           artifact: E7_Blinky_HE },
          { tool: GCC,   dir: ./DevKit-e7/Examples/Blinky_HP,            proj: Blinky_HP,           artifact: E7_Blinky_HP },
          { tool: AC6,   dir: ./DevKit-e7/Examples/Blinky_HP,            proj: Blinky_HP,           artifact: E7_Blinky_HP }
          ]

      fail-fast: false

    runs-on: ubuntu-latest

    steps:
      - name: Checkout .ci folder
        uses: actions/checkout@v4
        with:
          sparse-checkout: |
            .ci

      - name: Install tools
        uses: ARM-software/cmsis-actions/vcpkg@v1
        with:
          config: "./.ci/vcpkg-configuration.json"

      - name: Activate Arm tool license
        uses: ARM-software/cmsis-actions/armlm@v1

      - name: Checkout current repository
        uses: actions/checkout@v4
        with:
          path: ./DFP

      - name: Initialize CMSIS pack root folder
        run: |
          cpackget init https://www.keil.com/pack/index.pidx
          cpackget update-index

      - name: Add local CMSIS packs
        run: |
          cpackget add ./DFP/AlifSemiconductor.Ensemble.pdsc

      - name: Copy example to CI folder
        working-directory: ./
        run: |
          mkdir -p ./CI/${{ matrix.test.dir }}
          cp -a ./DFP/Boards/${{ matrix.test.dir }}/. ./CI/${{ matrix.test.dir }}

      - name: Build Example
        working-directory: ./CI/${{ matrix.test.dir }}
        run: |
          cbuild ./${{ matrix.test.proj }}.csolution.yml --packs --toolchain ${{ matrix.test.tool }}

      - name: Upload Artifact
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.test.artifact }}_${{ matrix.test.tool }}
          path: |
            ./CI/${{ matrix.test.dir }}/
            !./CI/${{ matrix.test.dir }}/tmp/
          retention-days: 1
